import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { studentDomains } from '../shared/student'
import { batchStatuses } from '../shared/learning'
import { useLearning, dateLabel } from './learning-api'
import { LearningAdminPage, LearningForm, LearningTable, LearningState, StatusBadge } from './learning-ui'

export function BatchAdmin() {
  const state = useLearning('/batches', true), catalog = useLearning('/catalog', true)
  const [editing, setEditing] = useState(null), [selected, setSelected] = useState(null)
  const [params] = useSearchParams()
  const fields = [{ key: 'name', label: 'Batch Name', required: true, maxLength: 160 }, { key: 'domain', label: 'Internship Domain', type: 'select', options: studentDomains, required: true }, { key: 'code', label: 'Batch Code', required: true, maxLength: 40 }, { key: 'startDate', label: 'Start Date', type: 'date', required: true }, { key: 'endDate', label: 'End Date', type: 'date', required: true }, { key: 'duration', label: 'Duration label', maxLength: 80 }, { key: 'mentor', label: 'Mentor / Trainer', required: true, maxLength: 120 }, { key: 'description', label: 'Description', type: 'textarea', maxLength: 4000 }, { key: 'maxStudents', label: 'Maximum Students', type: 'number', min: 1, max: 10000, required: true }, { key: 'applicationDeadline', label: 'Application Deadline', type: 'date' }, { key: 'status', label: 'Status', type: 'select', options: batchStatuses, required: true }, { key: 'enabled', label: 'Batch enabled', type: 'checkbox' }, { key: 'requiredVideos', label: 'Required Content Creation videos', type: 'checks', options: (catalog.data?.videos || []).map(item => ({ value: item._id, label: item.title })) }]
  const change = (item, body) => state.act(`/batches/${item._id}`, 'PATCH', body)
  return <LearningAdminPage title="Internship Batches" state={state}><LearningState state={catalog} /><button className="button button-dark" onClick={() => setEditing({ status: 'Draft', enabled: true, maxStudents: 30, domain: studentDomains[0], requiredVideos: [] })}>Create Batch</button>{editing && <LearningForm key={editing._id || 'new'} fields={fields} initial={editing} busy={state.busy} onCancel={() => setEditing(null)} onSave={async body => { if (await state.act(editing._id ? `/batches/${editing._id}` : '/batches', editing._id ? 'PATCH' : 'POST', body)) { setEditing(null); catalog.refresh() } }} />}
    <LearningTable rows={state.data || []} columns={[{ label: 'Batch', render: item => <><b>{item.name}</b><small>{item.code} · {item.domain}</small></> }, { label: 'Dates / Mentor', render: item => <>{dateLabel(item.startDate)} – {dateLabel(item.endDate)}<small>{item.mentor}</small></> }, { label: 'Enrollment', render: item => `${item.enrollmentCount}/${item.maxStudents}` }, { label: 'Status', render: item => <><StatusBadge value={item.status} />{!item.enabled && <small>Inactive</small>}</> }, { label: 'Actions', render: item => <div className="learning-actions"><button onClick={() => setSelected(item)}>View / Assign Students</button>{item.status !== 'Completed' && <><button onClick={() => setEditing(item)}>Edit</button><button onClick={() => change(item, { enabled: !item.enabled })}>{item.enabled ? 'Deactivate' : 'Activate'}</button>{item.status === 'Active' && <button onClick={() => { if (window.confirm('Complete this batch and preserve its enrollment history?')) change(item, { status: 'Completed' }) }}>Complete</button>}{item.status === 'Draft' && <button onClick={() => { if (window.confirm('Delete this unused draft batch?')) state.act(`/batches/${item._id}`, 'DELETE') }}>Delete draft</button>}</>}</div> }]} />
    {selected && <BatchMembers key={selected._id} batch={selected} catalog={catalog.data} applicationId={params.get('application') || ''} onChanged={state.refresh} onClose={() => setSelected(null)} />}
  </LearningAdminPage>
}
function BatchMembers({ batch, catalog, applicationId, onChanged, onClose }) {
  const state = useLearning(`/batches/${batch._id}/students`, true)
  return <section className="learning-card"><div className="learning-title"><h2>{batch.name}: students & history</h2><button onClick={onClose}>Close</button></div><LearningState state={state} />{['Upcoming', 'Active'].includes(batch.status) && batch.enabled && <LearningForm initial={{ studentId: '', applicationId, transfer: false }} fields={[{ key: 'studentId', label: 'Student', type: 'select', required: true, options: (catalog?.students || []).filter(item => item.internshipDomain === batch.domain).map(item => ({ value: item._id, label: `${item.fullName} · ${item.studentId}` })) }, { key: 'applicationId', label: 'Selected application ID (optional)' }, { key: 'transfer', label: 'Transfer from current batch, preserving history', type: 'checkbox' }]} busy={state.busy} submitLabel="Assign Student" onSave={async body => { if (await state.act(`/batches/${batch._id}/students`, 'POST', body)) onChanged() }} />}
    <LearningTable rows={state.data || []} columns={[{ label: 'Student', render: item => <>{item.student?.fullName}<small>{item.student?.studentId}</small></> }, { label: 'Status', render: item => <StatusBadge value={item.status} /> }, { label: 'Assigned / Ended', render: item => <>{dateLabel(item.createdAt)} / {dateLabel(item.endedAt)}</> }, { label: 'Action', render: item => item.status === 'Enrolled' && <button onClick={async () => { if (window.confirm('Remove this enrollment? Its history will be retained.') && await state.act(`/batches/${batch._id}/students/${item._id}`, 'DELETE')) onChanged() }}>Remove Student</button> }]} />
  </section>
}
