import { Link } from 'react-router-dom'
import { studentDomains } from '../shared/student'
import { useLearning, dateLabel } from './learning-api'
import { LearningAdminPage, LearningForm, LearningState, LearningTable } from './learning-ui'

export function NotificationsAdmin() {
  const state = useLearning('/notifications', true), catalog = useLearning('/catalog', true)
  return <LearningAdminPage title="Student Notifications" state={state}><LearningState state={catalog} /><p>Send an in-app update to one student or an internship domain. No email, WhatsApp or browser push is sent.</p><LearningForm initial={{ title: '', message: '', student: '', domain: '', href: '/student' }} fields={[{ key: 'title', label: 'Title', required: true, maxLength: 160 }, { key: 'message', label: 'Message', type: 'textarea', required: true, maxLength: 1000 }, { key: 'student', label: 'Specific Student (takes priority)', type: 'select', options: (catalog.data?.students || []).map(item => ({ value: item._id, label: `${item.fullName} · ${item.studentId}` })) }, { key: 'domain', label: 'Domain audience (if no specific student)', type: 'select', options: studentDomains }, { key: 'href', label: 'Open internal page', type: 'select', required: true, options: ['/student', '/student/tasks', '/student/certificates', '/student/internship', '/student/recorded-classes', '/news', '/tech-news'] }]} busy={state.busy} submitLabel="Send In-App Notification" onSave={body => { if (window.confirm('Send this in-app notification to the selected audience?')) state.act('/notifications', 'POST', body) }} /><h2>Recently sent</h2><LearningTable rows={state.data || []} columns={[{ label: 'Recipient', render: item => <>{item.student?.fullName}<small>{item.student?.studentId}</small></> }, { label: 'Title', render: item => item.title }, { label: 'Sent', render: item => dateLabel(item.createdAt) }, { label: 'Read', render: item => item.readAt ? dateLabel(item.readAt) : 'Unread' }]} /></LearningAdminPage>
}
export function GamificationAdmin() {
  return <section className="admin-page learning-page"><span className="eyebrow">Engagement</span><h1>Gamification & Leaderboard</h1><section className="learning-card"><h2>Participation is optional</h2><p>Enable Gamification and Leaderboard separately in Website Settings. Both default to OFF. Disabling either feature retains activity records.</p><Link className="button button-dark" to="/admin/website-settings">Manage engagement switches</Link><h3>Activity-based rewards</h3><ul><li>First authenticated dashboard visit: 10 XP / First Login.</li><li>First submission per task: 20 XP / First Task Submitted.</li><li>Approved or completed task: 40 XP once per task / Task Master after five.</li><li>Recorded class completion: 30 XP after 90% verified playback coverage.</li><li>Recorded learning day: 2 XP once per UTC day.</li><li>Discovery read: 5 XP once per item / Learning Explorer after five.</li><li>Completed batch: 100 XP once per batch / Internship Completed.</li></ul><p>The 7-Day Learner badge requires seven consecutive UTC days with tracked learning. Login alone does not extend a learning streak. Historical actions performed while Gamification was OFF receive no retroactive XP.</p><p>The leaderboard is available only to signed-in students and displays student IDs and XP. Students can exclude themselves from their progress dashboard.</p></section></section>
}
