import { useState } from 'react'
import { leadStatuses } from '../shared/learning'
import { resolveInternationalPhone } from '../shared/phone'
import { useLearning, dateLabel } from './learning-api'
import { LearningAdminPage, LearningTable, LearningForm, StatusBadge } from './learning-ui'

export function LeadsAdmin() {
  const [filter, setFilter] = useState(''), [due, setDue] = useState(false), [selected, setSelected] = useState(null)
  const state = useLearning(`/leads?status=${encodeURIComponent(filter)}&due=${due}`, true)
  const overdue = item => item.followUpDate && new Date(item.followUpDate) < new Date() && !['Completed', 'Closed', 'Converted'].includes(item.status)
  const phone = selected && resolveInternationalPhone(selected)
  return <LearningAdminPage title="Project Enquiries / Leads" state={state}><div className="learning-stats">{Object.entries(state.data?.summary || {}).map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="learning-actions"><label>Status <select value={filter} onChange={event => setFilter(event.target.value)}><option value="">All</option>{leadStatuses.map(value => <option key={value}>{value}</option>)}</select></label><label><input type="checkbox" checked={due} onChange={event => setDue(event.target.checked)} />Follow-ups Due</label></div><LearningTable rows={state.data?.items || []} columns={[{ label: 'Customer', render: item => <>{item.studentName}<small>{item.email}</small></> }, { label: 'Requested Project', render: item => item.projectTitle || item.project?.title || 'Project enquiry' }, { label: 'Status', render: item => <StatusBadge value={item.status} /> }, { label: 'Follow-up', render: item => <><span>{dateLabel(item.followUpDate)}</span>{overdue(item) && <StatusBadge value="Overdue" />}</> }, { label: 'Action', render: item => <button onClick={() => setSelected(item)}>View Lead</button> }]} />
    {selected && <section className="learning-card"><div className="learning-title"><h2>{selected.studentName}</h2><button onClick={() => setSelected(null)}>Close</button></div><dl className="learning-details"><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Phone</dt><dd>{phone?.formatInternational() || selected.phone || 'Not supplied'}</dd></div><div><dt>Requested Project</dt><dd>{selected.projectTitle || selected.project?.title}</dd></div><div><dt>Institution / Course</dt><dd>{selected.college} · {selected.degreeCourse}</dd></div></dl><p className="learning-prewrap">{selected.message}</p><div className="learning-actions">{phone && <a href={`tel:${phone.number}`}>Call</a>}<a href={`mailto:${selected.email}`}>Email</a>{phone && <a href={`https://wa.me/${phone.number.replace(/\D/g, '')}`} target="_blank" rel="noopener noreferrer">WhatsApp</a>}</div><LearningForm key={`${selected._id}-${selected.updatedAt}`} initial={{ status: selected.status, followUpDate: selected.followUpDate || '', note: '' }} fields={[{ key: 'status', label: 'Lead Status', type: 'select', options: leadStatuses, required: true }, { key: 'followUpDate', label: 'Follow-up Date (UTC)', type: 'datetime-local' }, { key: 'note', label: 'Add Internal Note', type: 'textarea', maxLength: 4000 }]} busy={state.busy} onSave={async body => { const saved = await state.act(`/leads/${selected._id}`, 'PATCH', { ...body, followUpDate: body.followUpDate ? `${String(body.followUpDate).slice(0,16)}Z` : null }); if (saved) setSelected({ ...selected, ...saved }) }} /><h3>Internal Notes</h3><div className="learning-timeline">{selected.internalNotes?.map(note => <article key={note._id}><small>{dateLabel(note.createdAt)}</small><p className="learning-prewrap">{note.text}</p></article>)}</div><details><summary>Status history</summary>{selected.statusHistory?.map(item => <p key={item._id}>{dateLabel(item.changedAt)} · {item.status}</p>)}</details></section>}
  </LearningAdminPage>
}
