import { useEffect, useState } from 'react'
import { adminFetch } from './api'

const label = key => key.replace(/([A-Z])/g, ' $1').replace(/^./, value => value.toUpperCase())
const settingsLabels = { batchesEnabled: 'Internship Batch System', tasksEnabled: 'Tasks & Assignments', certificateVerificationEnabled: 'Certificates & Public Verification', notificationsEnabled: 'Student Notifications', gamificationEnabled: 'Gamification', leaderboardEnabled: 'Leaderboard (requires Gamification)', newsEnabled: 'News (all news and discoveries)', internshipsEnabled: 'Internships section', discoverEnabled: 'Learn & Discover', discoverImportEnabled: 'External Content Import', discoverPublishingMode: 'External Content Publishing', projectsEnabled: 'Projects section', projectEnquiriesEnabled: 'Accept project enquiries', customRequestsEnabled: 'Accept custom project requests', internshipApplicationsEnabled: 'Internship applications', techNewsEnabled: 'Daily Tech News section', testimonialsEnabled: 'Testimonials section', contactEnabled: 'Contact form', whatsapp: 'WhatsApp number (country code + digits)' }
export function Switch({ title, checked, onChange, disabled = false }) { return <label className="management-switch"><input type="checkbox" role="switch" checked={checked} disabled={disabled} onChange={event => onChange(event.target.checked)} /><span>{title}</span><b>{checked ? 'ON' : 'OFF'}</b></label> }
function Frame({ title, children, error, message }) { return <section className="admin-page"><span className="eyebrow">Central management</span><h1>{title}</h1>{error && <p className="admin-error" role="alert">{error}</p>}{message && <p className="admin-notice" role="status">{message}</p>}{children}</section> }
function useRecords(path) {
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [version, setVersion] = useState(0)
  useEffect(() => { let active = true; adminFetch(path).then(value => { if (active) { setData(value); setError('') } }).catch(err => { if (active) setError(err.message) }); return () => { active = false } }, [path, version])
  const save = async (url, body, method = 'PUT') => { setBusy(true); setError(''); setMessage(''); try { await adminFetch(url, { method, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); setMessage('Changes saved.'); setVersion(value => value + 1); window.dispatchEvent(new Event('innovix-content-change')); return true } catch (err) { setError(err.message); return false } finally { setBusy(false) } }
  return { data, error, message, busy, save, retry: () => setVersion(value => value + 1) }
}
function Pending({ state }) { return state.error ? <button className="admin-button light" onClick={state.retry}>Retry</button> : <p role="status">Loading...</p> }

export function ConfigurationAdmin({ section }) {
  const state = useRecords('/configuration')
  return <Frame title={section === 'settings' ? 'Website Settings' : section === 'services' ? 'Services' : 'Homepage Content'} {...state}>{state.data ? <ConfigForm key={`${section}-${JSON.stringify(state.data[section])}`} section={section} initial={state.data[section]} state={state} /> : <Pending state={state} />}</Frame>
}
function ConfigForm({ section, initial, state }) {
  const [form, setForm] = useState(initial)
  return <form className="admin-editor" onSubmit={event => { event.preventDefault(); state.save(`/configuration/${section}`, form) }}><p>Changes become available through the website API without rebuilding. Open pages refresh settings automatically.</p>{section === 'settings' && <p>News controls the News hub, Daily Tech News and Learn &amp; Discover together. Their individual switches still apply. Internships controls the public section and new applications; enrolled students retain their learning resources.</p>}{section === 'services' ? <><div className="management-stack">{form.map((item, index) => <fieldset key={index}><legend>Service {index + 1}</legend><label>Title<input value={item.title} required maxLength={160} onChange={event => setForm(form.map((row, i) => i === index ? { ...row, title: event.target.value } : row))} /></label><label>Description<textarea value={item.description} maxLength={2000} onChange={event => setForm(form.map((row, i) => i === index ? { ...row, description: event.target.value } : row))} /></label><Switch title="Visible" checked={item.active} onChange={active => setForm(form.map((row, i) => i === index ? { ...row, active } : row))} /><button type="button" className="admin-button light" onClick={() => { if (window.confirm('Remove this service? Save to apply the change.')) setForm(form.filter((_, i) => i !== index)) }}>Remove</button></fieldset>)}</div><button type="button" className="admin-button light" onClick={() => setForm([...form, { title: '', description: '', active: true }])}>Add service</button></> : <div className="admin-form-grid">{Object.entries(form).map(([key, value]) => typeof value === 'boolean' ? <Switch key={key} title={settingsLabels[key] || label(key)} checked={value} onChange={next => setForm({ ...form, [key]: next })} /> : <label key={key}>{settingsLabels[key] || label(key)}{key === 'discoverPublishingMode' ? <select value={value} onChange={event => setForm({ ...form, [key]: event.target.value })}><option value="manual">Manual Approval</option><option value="auto">Auto Publish Trusted Sources</option></select> : ['heroSubtitle', 'aboutSummary', 'notice'].includes(key) ? <textarea value={value} maxLength={2000} onChange={event => setForm({ ...form, [key]: event.target.value })} /> : <input type={key.endsWith('Url') ? 'url' : key === 'supportEmail' ? 'email' : 'text'} value={value} maxLength={2000} onChange={event => setForm({ ...form, [key]: event.target.value })} />}</label>)}</div>}<button className="admin-button dark" disabled={state.busy}>{state.busy ? 'Saving...' : 'Save changes'}</button></form>
}

export function InternshipAdmin({ live = false }) {
  const state = useRecords('/internship-domains')
  return <Frame title={live ? 'Live Classes' : 'Internship Domains'} {...state}>{state.data ? <div className="management-stack">{state.data.map(item => <DomainForm key={JSON.stringify(item)} item={item} live={live} state={state} />)}</div> : <Pending state={state} />}</Frame>
}
function DomainForm({ item, live, state }) {
  const [form, setForm] = useState(item)
  const keys = live ? ['classTitle', 'meetingUrl', 'date', 'startTime', 'description', 'classActive'] : ['active', 'applicationsOpen', 'liveClassEnabled', 'recordedClassesEnabled']
  return <form className="admin-editor" onSubmit={event => { event.preventDefault(); state.save(`/internship-domains/${item._id}`, Object.fromEntries(keys.map(key => [key, form[key] ?? ''])), 'PATCH') }}><h2>{item.name}</h2>{!live && item.name !== 'Content Creation' && <p>Recorded-video storage currently serves Content Creation. Other domains can be configured here ahead of a future library integration.</p>}<div className="admin-form-grid">{keys.map(key => typeof form[key] === 'boolean' ? <Switch key={key} title={label(key)} checked={form[key]} onChange={value => setForm({ ...form, [key]: value })} /> : <label key={key}>{label(key)}<input type={key === 'meetingUrl' ? 'url' : key === 'date' ? 'date' : key === 'startTime' ? 'time' : 'text'} value={form[key] || ''} maxLength={2000} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><button className="admin-button dark" disabled={state.busy}>Save {live ? 'live class' : 'internship'}</button></form>
}

export function StudentsAdmin() {
  const [search, setSearch] = useState('')
  const [domain, setDomain] = useState('')
  const [status, setStatus] = useState('')
  const [selected, setSelected] = useState(null)
  const state = useRecords('/students')
  const rows = (state.data || []).filter(item => (!status || item.accountStatus === status) && (!domain || item.internshipDomain === domain) && [item.studentId, item.fullName, item.email, item.college].join(' ').toLowerCase().includes(search.toLowerCase()))
  return <Frame title="Students" {...state}><div className="admin-toolbar"><input className="admin-search" aria-label="Search students" placeholder="Search name, email, student ID or college" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label="Internship domain" value={domain} onChange={event => setDomain(event.target.value)}><option value="">All domains</option>{[...new Set((state.data || []).map(item => item.internshipDomain))].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Account status" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div>{!state.data ? <Pending state={state} /> : <><div className="management-table"><table><thead><tr>{['Student ID', 'Name / Email', 'Domain', 'Status', 'Registered', 'Actions'].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map(item => <tr key={item._id}><td>{item.studentId}</td><td>{item.fullName}<br />{item.email}</td><td>{item.internshipDomain}</td><td>{item.accountStatus}</td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><button className="admin-button light" onClick={() => setSelected(item)}>View profile</button><button className="admin-button light" disabled={state.busy} onClick={async () => { if (window.confirm(`${item.accountStatus === 'active' ? 'Suspend' : 'Activate'} ${item.fullName}? Existing sessions will be revoked.`)) { if (await state.save(`/students/${item._id}/account-status`, { accountStatus: item.accountStatus === 'active' ? 'suspended' : 'active' }, 'PATCH')) setSelected(null) } }}>{item.accountStatus === 'active' ? 'Suspend' : 'Activate'}</button></td></tr>)}</tbody></table></div>{!rows.length && <p className="admin-empty">No students match these filters.</p>}</>}{selected && <section className="admin-record" aria-label="Student profile"><h2>{selected.fullName}</h2><dl className="admin-details">{Object.entries(selected).filter(([key]) => key !== '_id').map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{key === 'createdAt' ? new Date(value).toLocaleString() : value}</dd></div>)}</dl><button className="admin-button light" onClick={() => setSelected(null)}>Close profile</button></section>}</Frame>
}

const blankAnnouncement = { title: '', message: '', type: 'Information', startDate: '', endDate: '', active: false }
export function AnnouncementsAdmin() {
  const state = useRecords('/announcements')
  const [form, setForm] = useState(blankAnnouncement)
  return <Frame title="Announcements" {...state}><form className="admin-editor" onSubmit={async event => { event.preventDefault(); if (await state.save(form._id ? `/announcements/${form._id}` : '/announcements', Object.fromEntries(Object.keys(blankAnnouncement).map(key => [key, form[key]])), form._id ? 'PUT' : 'POST')) setForm(blankAnnouncement) }}><h2>{form._id ? 'Edit announcement' : 'New announcement'}</h2><div className="admin-form-grid"><label>Title<input required maxLength={160} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label>Type<select value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}>{['Information', 'Success', 'Warning', 'Important'].map(value => <option key={value}>{value}</option>)}</select></label><label className="admin-span">Message<textarea required maxLength={2000} value={form.message} onChange={event => setForm({ ...form, message: event.target.value })} /></label>{['startDate', 'endDate'].map(key => <label key={key}>{label(key)} (UTC)<input type="datetime-local" value={form[key] ? form[key].slice(0, 16) : ''} onChange={event => setForm({ ...form, [key]: event.target.value ? `${event.target.value}:00.000Z` : '' })} /></label>)}<Switch title="Active" checked={form.active} onChange={active => setForm({ ...form, active })} /></div><button className="admin-button dark" disabled={state.busy}>Save announcement</button>{form._id && <button className="admin-button light" type="button" onClick={() => setForm(blankAnnouncement)}>Cancel edit</button>}</form>{!state.data ? <Pending state={state} /> : state.data.length ? state.data.map(item => <article className="admin-record" key={item._id}><span className="status">{item.active ? 'Active' : 'Inactive'} · {item.type}</span><h2>{item.title}</h2><p>{item.message}</p><div className="admin-actions"><button className="admin-button light" onClick={() => setForm({ ...blankAnnouncement, ...item, startDate: item.startDate || '', endDate: item.endDate || '' })}>Edit / Preview</button><button className="admin-button light" disabled={state.busy} onClick={() => state.save(`/announcements/${item._id}`, { active: !item.active })}>{item.active ? 'Turn off' : 'Turn on'}</button><button className="admin-button light" disabled={state.busy} onClick={() => { if (window.confirm('Delete this announcement permanently?')) state.save(`/announcements/${item._id}`, undefined, 'DELETE') }}>Delete</button></div></article>) : <p className="admin-empty">No announcements yet.</p>}</Frame>
}
export function AdminSettings() {
  const state = useRecords('/profile')
  const log = useRecords('/activity')
  return <Frame title="Admin Settings" {...state}>{state.data ? <section className="admin-record"><h2>Administrator account</h2><p>{state.data.email} · {state.data.role}</p><p>This account provides access to every management module. Use the existing server administrator tools for credential changes; secrets are not stored in website settings.</p></section> : <Pending state={state} />}<h2>Admin activity</h2>{log.error && <p role="alert">{log.error}</p>}{log.data ? <div className="management-table"><table><thead><tr><th>Action</th><th>Target</th><th>Timestamp</th></tr></thead><tbody>{log.data.map(item => <tr key={item._id}><td>{item.action}</td><td>{item.target}</td><td>{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!log.data.length && <p>No recorded actions yet.</p>}</div> : <Pending state={log} />}</Frame>
}
