import { Link } from 'react-router-dom'
import { ArrowRight, Award, BookOpen, Check, Compass, FileText, Laptop, Rocket, Sparkles } from 'lucide-react'
import { internshipRoles } from './data'
import { SectionHeading } from './components'

const internshipBenefits = [
  ['Learn by doing', 'Practice on real-time project work with technical guidance and feedback.'],
  ['Build your portfolio', 'Turn completed work into examples you can explain and share.'],
  ['Prepare for your next step', 'Get support with your resume, LinkedIn profile, and career-focused skills.'],
  ['Document your experience', 'Complete the program with an internship certificate.'],
]

const packages = [
  { name: 'Basic', price: '₹2,999', description: 'A standard academic project package with the project materials and guidance needed to get started.', features: ['Project development', 'Source code and explanation', 'Documentation guidance'], action: 'Get Started', to: '/projects' },
  { name: 'Intermediate', price: '₹3,999', description: 'For students who need more guidance while developing, understanding, and presenting their project.', features: ['Project development support', 'Step-by-step technical guidance', 'Documentation and presentation guidance'], action: 'Enquire Now', to: '/build-your-project' },
  { name: 'Professional', price: '₹4,999', description: 'A higher-support package for students who want closer help with their project from planning through final submission.', features: ['Project planning and development support', 'Technical and output guidance', 'Documentation, PPT, and viva preparation'], action: 'Contact Us', to: '/contact', featured: true },
]

export function HomeInternship() {
  return <section className="section home-internship" id="internship-highlight"><div className="container home-internship-grid">
    <div className="home-internship-intro"><span className="eyebrow">Internships at Innovix</span><h2>Learn the work.<br /><em>Then do the work.</em></h2><p>Explore internship opportunities built around practical learning, real-time project exposure, technical guidance, and skills you can carry into your career.</p><div className="home-internship-actions"><a className="button button-light" href="/internships#internship-application">Apply Now <ArrowRight size={16} /></a><Link className="text-link" to="/internships">Explore Internships <ArrowRight size={16} /></Link></div><span className="home-internship-note">Open to students from different academic backgrounds.</span></div>
    <div className="home-internship-benefits">{internshipBenefits.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{description}</p></div><Check size={18} /></article>)}</div>
  </div></section>
}

export function InternshipDomains() {
  return <section className="section container home-opportunities"><SectionHeading eyebrow="Internship opportunities" title="Find a track to grow in." description="Choose a role that matches your interests. Your course or degree does not have to be in Computer Science." action={<Link className="text-link" to="/internships">See the internship program <ArrowRight size={16} /></Link>} /><div className="opportunity-grid">{internshipRoles.map((role, index) => <a href="/internships#internship-application" className="opportunity-card" key={role}><span>0{index + 1}</span><h3>{role}</h3><ArrowRight size={17} /></a>)}</div></section>
}

export function PricingSection({ compact = false }) {
  return <section className={compact ? 'section pricing-section pricing-compact' : 'section pricing-section'}><div className="container"><SectionHeading eyebrow="Project packages" title="Choose the support that fits." description="Projects starting from ₹2,999. Each saved project keeps its own listed price; these packages describe the level of support available." /><div className="pricing-grid">{packages.map((item) => <article className={item.featured ? 'pricing-card featured' : 'pricing-card'} key={item.name}><span className="eyebrow">{item.name}</span><strong>{item.price}</strong><p>{item.description}</p><ul>{item.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><Link className={item.featured ? 'button button-light' : 'button button-outline'} to={item.to}>{item.action} <ArrowRight size={16} /></Link></article>)}</div></div></section>
}

export function AboutPage() {
  return <>
    <section className="about-hero"><div className="container"><span className="eyebrow">About Innovix Projects</span><h1>Experience that helps you<br /><em>move forward.</em></h1><p>Innovix Projects is a student-focused platform for internships, practical learning, real-time project exposure, skill development, academic project work, and technical guidance.</p><div className="about-hero-actions"><a className="button button-dark" href="/internships#internship-application">Apply for an Internship <ArrowRight size={16} /></a><Link className="button button-outline" to="/projects">Explore Projects <ArrowRight size={16} /></Link></div></div></section>
    <section className="section container about-service"><div className="about-service-heading"><span className="eyebrow">01 / Internships first</span><h2>Practice, guidance, and work you can show.</h2><p>Our internship program gives students room to learn by doing. Explore a role, work through practical tasks and real-time project briefs, and develop the confidence to explain your decisions.</p><a className="button button-dark" href="/internships#internship-application">Apply Now <ArrowRight size={16} /></a></div><div className="about-service-grid"><article><Laptop /><h3>Hands-on experience</h3><p>Build practical skills through guided work across frontend, design, Python, content, security, and full stack roles.</p></article><article><Compass /><h3>Technical direction</h3><p>Get guidance as you plan, build, review, and improve your work. Students from varied academic backgrounds are welcome.</p></article><article><BookOpen /><h3>Career materials</h3><p>Develop portfolio examples and receive support in presenting your experience on a resume and LinkedIn profile.</p></article><article><Award /><h3>Completion certificate</h3><p>Document the experience and skills developed during the internship program.</p></article></div></section>
    <section className="section about-tracks"><div className="container"><SectionHeading eyebrow="Explore opportunities" title="Multiple ways to put learning into practice." description="Choose a track that fits your interests, then use the existing internship application to tell us about yourself." /><div className="about-track-list">{internshipRoles.map((role) => <span key={role}>{role}</span>)}</div><p className="about-track-note">The program connects practical tasks with industry-oriented ways of working, helping you build experience and career-focused skills through practice.</p></div></section>
    <section className="section container about-service about-project-service"><div className="about-service-heading"><span className="eyebrow">02 / Project development</span><h2>Understand what you build.</h2><p>We support academic and technical projects with planning, development, step-by-step explanation, and guidance for documentation, output, PPT presentations, and viva preparation.</p><p>Students can choose an existing project or bring a custom idea. Support is focused on helping you complete and explain your work through final submission.</p><div className="about-service-actions"><Link className="button button-dark" to="/projects">Explore Projects <ArrowRight size={16} /></Link><Link className="button button-outline" to="/build-your-project">Build Your Project <ArrowRight size={16} /></Link></div></div><div className="about-project-panel"><Sparkles size={26} /><span className="eyebrow">Projects starting from</span><strong>₹2,999</strong><p>Basic ₹2,999 · Intermediate ₹3,999 · Professional ₹4,999</p><div><FileText size={16} /> Documentation and presentation guidance</div><div><Rocket size={16} /> Custom project support when you need it</div></div></section>
    <PricingSection compact />
    <section className="section container about-principles"><div><span className="eyebrow">Why Innovix</span><h2>Support for the work ahead.</h2><p>We want practical learning and clear technical guidance to feel approachable for students at different stages and from different academic backgrounds.</p></div><div className="about-values"><div><Sparkles /><b>Our mission</b><p>Help students gain hands-on experience and complete meaningful academic and technical work with guidance they can understand.</p></div><div><Rocket /><b>Our vision</b><p>Students who learn by creating, can explain what they have built, and feel prepared for their next step.</p></div></div></section>
    <section className="section container about-contact"><h2>Have a question about an internship or project?</h2><p>Tell us what you are studying and what kind of support you need.</p><Link className="button button-dark" to="/contact">Contact Innovix <ArrowRight size={16} /></Link></section>
  </>
}
