import { useState } from 'react'
import { PaymentSection } from './InternshipCourse'
import { Link, useSearchParams } from 'react-router-dom'
import { useSite } from './site-context'
import { useStudentSession } from './student-session-context'
import { useLearning, dateLabel } from './learning-api'
import { LearningState, LearningForm, LearningUpload, LearningFileLink, StatusBadge } from './learning-ui'
import { SubmissionHistory } from './TaskAdmin'
import { daysUntil, taskTab } from '../shared/learning'

export function LearningStages({ stages }) {
  return <section className="learning-card" aria-label="Learning stages"><h3>Videos → Tasks → Projects → Certificate</h3><ol className="learning-task-grid">{stages.steps.map(step => <li className="learning-card" key={step.name}><h4>{step.name}</h4><StatusBadge value={step.status} />{step.total !== undefined && <p>{step.completed}/{step.total} required {step.name.toLowerCase()}</p>}<p>{step.message}</p>{step.status !== 'Locked' && <Link className="text-link" to={step.href}>View {step.name}</Link>}</li>)}</ol></section>
}

export function StudentLearningProgress() {
  const state = useLearning('/progress'), { settings } = useSite()
  return <section className="learning-page" id="learning-progress"><div className="learning-title"><div><span className="eyebrow">Your learning journey</span><h2>Progress, one step at a time.</h2></div><button className="button button-outline" onClick={state.refresh}>Refresh Progress</button></div><LearningState state={state} />{state.data && <ProgressOverview data={state.data} settings={settings} />}{settings.gamificationEnabled && <StudentAchievements />}</section>
}
export function ProgressOverview({ data, settings }) {
  const batch = data.enrollment?.batch, progress = data.internshipProgress
  const stats = [...(settings.tasksEnabled ? [['Tasks Assigned', data.tasksAssigned], ['Tasks Completed', data.tasksCompleted], ['Tasks Pending', data.tasksPending]] : []), ['Videos Watched', data.videosWatched], ['Discoveries Read', data.discoveriesRead]]
  return <>{data.payment && <PaymentSection payment={data.payment} />}{data.stages && <LearningStages stages={data.stages} />}<div className="learning-stats">{stats.map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>{settings.batchesEnabled && <section className="learning-card"><span className="eyebrow">My Internship</span>{batch ? <><div className="learning-title"><h3>{batch.name}</h3><StatusBadge value={data.enrollment.status === 'Enrolled' ? batch.status : data.enrollment.status} /></div><dl className="learning-details"><div><dt>Domain</dt><dd>{batch.domain}</dd></div><div><dt>Batch Code</dt><dd>{batch.code}</dd></div><div><dt>Mentor</dt><dd>{batch.mentor}</dd></div><div><dt>Start / End</dt><dd>{dateLabel(batch.startDate)} – {dateLabel(batch.endDate)}</dd></div></dl>{progress && <><label className="learning-progress-label">Internship date progress <b>{progress.percent}%</b><progress max="100" value={progress.percent} /></label><p>{progress.daysCompleted} days completed · {progress.daysRemaining} days remaining</p><small>Elapsed batch dates; certificate completion also requires the work below.</small></>}</> : <p>No batch assigned yet. Your batch details will appear after an administrator enrolls you.</p>}</section>}
    <div className="learning-columns">{settings.tasksEnabled && <section className="learning-card"><h3>Upcoming Tasks</h3>{data.upcoming.length ? data.upcoming.map(item => <Link className="learning-list-item" key={item._id} to="/student/tasks"><b>{item.title}</b><span>Due {dateLabel(item.dueDate)} · {daysUntil(item.dueDate) < 0 ? 'Overdue' : `${daysUntil(item.dueDate)} days remaining`}</span></Link>) : <p>No pending deadlines.</p>}<Link className="text-link" to="/student/tasks">View My Tasks →</Link></section>}{settings.certificateVerificationEnabled && <section className="learning-card"><h3>Certificate Eligibility</h3>{data.eligibility ? <><StatusBadge value={data.eligibility.eligible ? 'Eligible for admin review' : 'In progress'} /><p>{data.eligibility.eligible ? 'Your requirements are complete. An administrator must review and issue your certificate.' : data.eligibility.reasons.join(' ')}</p><p>{data.eligibility.completedTasks}/{data.eligibility.requiredTasks} required tasks · {data.eligibility.completedVideos}/{data.eligibility.requiredVideos} required videos ? {data.eligibility.completedProjects ?? 0}/{data.eligibility.requiredProjects ?? 0} required projects</p></> : <p>Eligibility will appear when you join a batch.</p>}<Link className="text-link" to="/student/certificates">My Certificates →</Link></section>}</div>
    <section className="learning-card"><h3>Recent Activity</h3>{data.activity.length ? <div className="learning-timeline">{data.activity.map(item => <article key={item._id}><b>{item.label}</b><small>{dateLabel(item.createdAt)}</small></article>)}</div> : <p>Your recorded learning activity will appear here.</p>}</section>{settings.batchesEnabled && data.history.length > 0 && <details className="learning-card"><summary>Enrollment timeline</summary><div className="learning-timeline">{data.history.map(item => <article key={item._id}><b>{item.batch?.name || 'Historical batch'}</b><StatusBadge value={item.status} /><p>{dateLabel(item.createdAt)} – {dateLabel(item.endedAt)}</p></article>)}</div></details>}</>
}
export function StudentTasks() {
  const { settings } = useSite(), { csrfToken } = useStudentSession()
  const state = useLearning(settings.tasksEnabled ? '/tasks' : null), [tab, setTab] = useState('Pending'), [selected, setSelected] = useState(null), [file, setFile] = useState(null)
  const [searchParams, setSearchParams] = useSearchParams(), stage = searchParams.get('stage') === 'Project' ? 'Project' : 'Task'
  const progressState = useLearning('/progress')
  if (!settings.tasksEnabled) return <section className="section container">Tasks are currently unavailable.</section>
  const tasks = (state.data || []).filter(item => taskTab(item) === tab && (item.stage || 'Task') === stage)
  return <section className="section container learning-page"><Link className="back-link" to="/student">← Student Dashboard</Link><span className="eyebrow">Practice your craft</span><h1>{stage === 'Project' ? 'Final Projects' : 'My Tasks'}</h1><button className="button button-outline" onClick={() => { state.refresh(); progressState.refresh() }}>Refresh progress and work</button><LearningState state={progressState} />{progressState.data?.stages && <LearningStages stages={progressState.data.stages} />}<nav className="learning-tabs" aria-label="Learning stage">{['Task', 'Project'].map(value => <button key={value} aria-pressed={stage === value} onClick={() => { setSearchParams(value === 'Project' ? { stage: value } : {}); setSelected(null); setFile(null) }}>{value === 'Project' ? 'Final Projects' : 'Tasks'}</button>)}</nav><LearningState state={state} /><nav className="learning-tabs" aria-label="Task status">{['Pending', 'Submitted', 'Reviewed', 'Completed'].map(value => <button key={value} aria-pressed={tab === value} onClick={() => { setTab(value); setSelected(null); setFile(null) }}>{value}</button>)}</nav><div className="learning-task-grid">{tasks.map(item => <article key={item._id} className="learning-card"><StatusBadge value={item.submission?.status || 'Not Submitted'} /><h2>{item.title}</h2><p>{item.description}</p><p>Assigned {dateLabel(item.assignedDate)} · Due {dateLabel(item.dueDate)}</p><small>{daysUntil(item.dueDate) < 0 ? 'Past due' : `${daysUntil(item.dueDate)} days remaining`} · {item.status}</small><button className="button button-outline" onClick={() => { setSelected(item); setFile(null) }}>{item.stage === 'Project' ? 'Open Project' : 'Open Task'}</button></article>)}</div>{!state.loading && !state.error && !tasks.length && <p className="learning-empty">No {tab.toLowerCase()} tasks.</p>}
    {selected && <section className="learning-card"><div className="learning-title"><h2>{selected.title}</h2><button onClick={() => setSelected(null)}>Close</button></div><p className="learning-prewrap">{selected.instructions}</p>{selected.referenceUrl && <p><a href={selected.referenceUrl} target="_blank" rel="noopener noreferrer">Reference material ↗</a></p>}{selected.attachment && <LearningFileLink id={selected.attachment} />}{selected.submission && <SubmissionHistory revisions={selected.submission.revisions} />}{selected.status === 'Published' && (!selected.submission || selected.submission.status === 'Resubmit') ? <><p>{selected.stage === 'Project' ? 'Upload your final project file. Admin will review and approve it.' : 'Choose at least one enabled submission method.'} Late submissions are marked for your reviewer.</p>{selected.methods.includes('file') && <LearningUpload key={selected._id} taskId={selected._id} csrfToken={csrfToken} onUploaded={setFile} />}<LearningForm key={`${selected._id}-${selected.submission?.version || 0}`} initial={{ text: '', github: '', demo: '' }} fields={[{ key: 'text', label: 'Text response', type: 'textarea', maxLength: 12000 }, { key: 'github', label: 'GitHub repository URL', type: 'url' }, { key: 'demo', label: 'Project / Demo URL', type: 'url' }].filter(field => selected.methods.includes(field.key))} busy={state.busy} submitLabel={selected.submission ? 'Submit Updated Version' : selected.stage === 'Project' ? 'Submit Project' : 'Submit Task'} onSave={async body => { if (await state.act(`/tasks/${selected._id}/submit`, 'POST', { ...body, ...(file ? { file: file._id } : {}) }, csrfToken)) { setSelected(null); setFile(null); setTab('Submitted') } }} /></> : <p>Submissions are {selected.status === 'Closed' ? 'closed' : 'with your mentor. You can resubmit when changes are requested'}.</p>}</section>}
  </section>
}
export function StudentCertificates() {
  const { settings } = useSite(), state = useLearning(settings.certificateVerificationEnabled ? '/progress' : null)
  return <section className="section container learning-page"><Link className="back-link" to="/student">← Student Dashboard</Link><h1>My Certificates</h1>{settings.certificateVerificationEnabled ? <><LearningState state={state} /><div className="learning-task-grid">{state.data?.certificates.map(item => <article className="learning-card" key={item._id}><StatusBadge value={item.status} /><h2>{item.type}</h2><p>{item.batchName}</p><p>{item.certificateId}</p><p>Issued {dateLabel(item.issueDate)}</p><Link className="button button-outline" to={`/verify/${item.certificateId}`}>View Verification</Link></article>)}</div>{state.data && !state.data.certificates.length && <p className="learning-empty">No certificates issued yet. Your mentor will review your completed requirements.</p>}</> : <p>Certificates are currently unavailable.</p>}</section>
}
function StudentAchievements() {
  const state = useLearning('/gamification'), { csrfToken } = useStudentSession(), { settings } = useSite()
  const board = useLearning(settings.leaderboardEnabled ? '/leaderboard' : null)
  return <section className="learning-card"><h3>Your Achievements</h3><LearningState state={state} />{state.data && <><p><strong>{state.data.xp} XP</strong> · {state.data.streak} day learning streak</p><div className="learning-actions">{state.data.badges.map(badge => <StatusBadge key={badge} value={badge} />)}</div>{!state.data.badges.length && <p>Complete learning activities to earn your first badge.</p>}<label className="learning-optout"><input type="checkbox" checked={state.data.leaderboardExcluded} disabled={state.busy} onChange={event => state.act('/leaderboard-preference', 'PUT', { excluded: event.target.checked }, csrfToken)} />Keep me off the leaderboard</label></>}{settings.leaderboardEnabled && <><h4>Learning Leaderboard</h4><p>Student IDs only. Participation is optional.</p><LearningState state={board} /><ol className="learning-leaderboard">{board.data?.map(item => <li key={item.studentId}><span>{item.studentId}</span><b>{item.xp} XP</b></li>)}</ol>{board.data?.length === 0 && <p>No participating learners yet.</p>}</>}</section>
}
