import { useState } from 'react'
import { studentDomains } from '../shared/student'
import { taskStatuses, submissionMethods } from '../shared/learning'
import { useLearning, dateLabel } from './learning-api'
import { LearningAdminPage, LearningForm, LearningState, LearningTable, LearningUpload, LearningFileLink, StatusBadge } from './learning-ui'

export function TaskAdmin() {
  const state = useLearning('/tasks', true), catalog = useLearning('/catalog', true)
  const [editing, setEditing] = useState(null), [attachment, setAttachment] = useState(null)
  const fields = [{ key: 'title', label: 'Task Title', required: true, maxLength: 160 }, { key: 'domain', label: 'Internship Domain', type: 'select', options: studentDomains, required: true }, { key: 'scope', label: 'Assign to', type: 'select', options: ['Domain', 'Batch', 'Student'], required: true }, { key: 'batch', label: 'Batch (for batch assignment)', type: 'select', options: (catalog.data?.batches || []).map(item => ({ value: item._id, label: item.name })) }, { key: 'student', label: 'Student (for student assignment)', type: 'select', options: (catalog.data?.students || []).map(item => ({ value: item._id, label: `${item.fullName} · ${item.studentId}` })) }, { key: 'description', label: 'Description', type: 'textarea', required: true, maxLength: 2000 }, { key: 'instructions', label: 'Instructions', type: 'textarea', maxLength: 8000 }, { key: 'assignedDate', label: 'Assigned Date (UTC)', type: 'datetime-local', required: true }, { key: 'dueDate', label: 'Due Date (UTC)', type: 'datetime-local', required: true }, { key: 'maximumMarks', label: 'Maximum Marks (optional)', type: 'number', min: 1, max: 10000 }, { key: 'referenceUrl', label: 'Reference URL', type: 'url' }, { key: 'methods', label: 'Allowed submission methods (at least one)', type: 'checks', options: submissionMethods }, { key: 'required', label: 'Required for certificate eligibility', type: 'checkbox' }, { key: 'status', label: 'Status', type: 'select', options: taskStatuses, required: true }]
  return <LearningAdminPage title="Tasks & Assignments" state={state}><LearningState state={catalog} /><button className="button button-dark" onClick={() => setEditing({ status: 'Draft', domain: studentDomains[0], scope: 'Domain', assignedDate: new Date().toISOString(), methods: [...submissionMethods], required: true })}>Create Task</button>{editing && <LearningForm key={editing._id || 'new'} initial={editing} fields={fields} busy={state.busy} onCancel={() => setEditing(null)} onSave={async body => { const data = await state.act(editing._id ? `/tasks/${editing._id}` : '/tasks', editing._id ? 'PATCH' : 'POST', { ...body, assignedDate: new Date(`${String(body.assignedDate).slice(0,16)}Z`).toISOString(), dueDate: new Date(`${String(body.dueDate).slice(0,16)}Z`).toISOString() }); if (data) { setEditing(null); setAttachment(data) } }} />}
    {attachment && <section className="learning-card"><h2>Attachment: {attachment.title}</h2><LearningUpload admin taskId={attachment._id} onUploaded={() => state.refresh()} /><button onClick={() => setAttachment(null)}>Done</button></section>}
    <LearningTable rows={state.data || []} columns={[{ label: 'Task', render: item => <><b>{item.title}</b><small>{item.domain} · {item.scope}</small></> }, { label: 'Due', render: item => dateLabel(item.dueDate) }, { label: 'Status', render: item => <StatusBadge value={item.status} /> }, { label: 'Actions', render: item => <div className="learning-actions"><button onClick={() => setEditing(item)}>Edit</button><button onClick={() => setAttachment(item)}>Attachment</button>{item.attachment && <LearningFileLink id={item.attachment} admin />}<button onClick={() => state.act(`/tasks/${item._id}`, 'PATCH', { status: item.status === 'Published' ? 'Closed' : 'Published' })}>{item.status === 'Published' ? 'Close' : 'Publish'}</button></div> }]} />
  </LearningAdminPage>
}
export function SubmissionsAdmin() {
  const state = useLearning('/submissions', true), [selected, setSelected] = useState(null)
  return <LearningAdminPage title="Submission Reviews" state={state}><LearningTable rows={state.data || []} columns={[{ label: 'Student', render: item => <>{item.student?.fullName}<small>{item.student?.studentId}</small></> }, { label: 'Task', render: item => item.task?.title }, { label: 'Status', render: item => <StatusBadge value={item.status} /> }, { label: 'Submitted', render: item => dateLabel(item.revisions.at(-1)?.submittedAt) }, { label: 'Action', render: item => <button onClick={() => setSelected(item)}>Review / History</button> }]} />{selected && <section className="learning-card"><h2>{selected.task?.title}</h2><SubmissionHistory revisions={selected.revisions} admin /><LearningForm key={`${selected._id}-${selected.version}`} initial={{ status: 'Under Review', feedback: '', marks: '' }} fields={[{ key: 'status', label: 'Review Status', type: 'select', options: ['Under Review', 'Approved', 'Resubmit', 'Completed'], required: true }, { key: 'feedback', label: 'Mentor Feedback', type: 'textarea', maxLength: 4000 }, ...(selected.task?.maximumMarks ? [{ key: 'marks', label: `Marks / ${selected.task.maximumMarks}`, type: 'number', min: 0, max: selected.task.maximumMarks }] : [])]} busy={state.busy} onCancel={() => setSelected(null)} onSave={async body => { if (await state.act(`/submissions/${selected._id}`, 'PATCH', { ...body, version: selected.version })) setSelected(null) }} /></section>}</LearningAdminPage>
}
export function SubmissionHistory({ revisions, admin = false }) {
  return <div className="learning-timeline">{revisions.map((item, index) => <article key={item._id || index}><b>Revision {index + 1} · {dateLabel(item.submittedAt)}</b>{item.late && <StatusBadge value="Late" />}{item.text && <p className="learning-prewrap">{item.text}</p>}{['github', 'demo'].map(key => item[key] && <p key={key}><a href={item[key]} target="_blank" rel="noopener noreferrer">{key === 'github' ? 'GitHub repository' : 'Project / demo'}</a></p>)}{item.file && <LearningFileLink id={item.file} admin={admin} />}{item.reviewedAt && <><p><StatusBadge value={item.reviewStatus} /> Reviewed {dateLabel(item.reviewedAt)}{item.marks != null && ` · Marks: ${item.marks}`}</p><p className="learning-prewrap">{item.feedback}</p></>}</article>)}</div>
}
